// gen-chroma-css writes a chroma stylesheet to stdout. One run produces one
// palette, each scoped so the two files are mutually exclusive in the
// cascade:
//
//	-style=light → rules prefixed by `html:not([data-theme="dark"])`
//	-style=dark  → rules prefixed by `[data-theme="dark"]`
//
// Mutual exclusion matters because chroma's github and github-dark styles
// cover different token-class sets (e.g. github defines `.nx`/`.na`/`.p`,
// github-dark does not). If both palettes applied to the same DOM tree, the
// dark page would render those uncovered tokens with light-theme dark-gray
// foreground colors that are invisible against the dark wrapper background.
// The `:not` scope keeps light rules out of dark pages entirely; uncovered
// tokens then inherit the dark wrapper's `color`.
//
// Run twice to refresh the leyline_base theme:
//
//	go run ./cmd/gen-chroma-css -style=light > .../static/chroma-light.css
//	go run ./cmd/gen-chroma-css -style=dark  > .../static/chroma-dark.css
//
// Re-generate when chroma updates a style or you swap palette choice; each
// file is small (~7 KB) and is intended to be committed.
package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	chromahtml "github.com/alecthomas/chroma/v2/formatters/html"
	"github.com/alecthomas/chroma/v2/styles"
)

const (
	lightSelectorPrefix = `html:not([data-theme="dark"]) `
	darkSelectorPrefix  = `[data-theme="dark"] `
)

func main() {
	style := flag.String("style", "", "palette to emit: light | dark")
	flag.Parse()
	if err := run(os.Stdout, *style); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(out *os.File, style string) error {
	var (
		styleName string
		prefix    string
	)
	switch style {
	case "light":
		styleName = "github"
		prefix = lightSelectorPrefix
	case "dark":
		styleName = "github-dark"
		prefix = darkSelectorPrefix
	default:
		return fmt.Errorf("-style must be %q or %q", "light", "dark")
	}

	chromaStyle := styles.Get(styleName)
	if chromaStyle == nil {
		return fmt.Errorf("style %q not registered", styleName)
	}

	var sb strings.Builder
	f := chromahtml.New(chromahtml.WithClasses(true))
	if err := f.WriteCSS(&sb, chromaStyle); err != nil {
		return fmt.Errorf("write %s css: %w", style, err)
	}

	fmt.Fprintln(out, "/* Auto-generated by cmd/gen-chroma-css. Do not edit. */")
	fmt.Fprintf(out, "/* chroma palette: %s (-style=%s). */\n\n", styleName, style)

	for _, line := range strings.Split(strings.TrimRight(sb.String(), "\n"), "\n") {
		if line == "" {
			fmt.Fprintln(out)
			continue
		}
		fmt.Fprintln(out, prefixRule(line, prefix))
	}
	return nil
}

// prefixRule inserts a theme-scope ancestor selector before the selector of a
// chroma CSS rule. Chroma emits each rule as a single line shaped like
// `/* Comment */ .selector { decls }`; the prefix slots in between the
// comment and the selector. Lines without that comment marker (defensive —
// shouldn't happen with current chroma) get the prefix applied to the entire
// line.
func prefixRule(line, prefix string) string {
	const marker = "*/ "
	if idx := strings.Index(line, marker); idx >= 0 {
		head := line[:idx+len(marker)]
		tail := line[idx+len(marker):]
		return head + prefix + tail
	}
	return prefix + line
}
