package search

import (
	"bufio"
	"bytes"
	"context"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	// coverageFloor is the minimum fraction of query grams a document must
	// contain to appear in results. 0.6 means for a 5-gram query the doc
	// must contain at least 3 grams.
	coverageFloor = 0.6

	// defaultTopK is the default maximum result count.
	defaultTopK = 20

	// snippetLen is the target snippet character length.
	snippetLen = 160
)

// Result is one entry in the search response.
type Result struct {
	Path       string
	URL        string
	Title      string
	Score      float64
	Snippet    string
	Highlights [][2]int // [start, end] rune (code-point) offsets in Snippet
}

// QueryOptions tunes a single query execution.
type QueryOptions struct {
	// VaultRoot is the on-disk vault directory, used to read files for
	// snippet generation. Required.
	VaultRoot string
	// VaultPrefix is the HTTP prefix for the vault (e.g. "/" or "/myrepo"),
	// used to build result URLs.
	VaultPrefix string
	// TopK caps the number of results returned. Zero → defaultTopK.
	TopK int
}

// Query scores all documents against q and returns the top-K results. It is
// the core search path: O(docs) scan, coverage-filtered, multi-field boosted,
// with per-result snippets generated by re-reading files.
func (idx *Index) Query(ctx context.Context, q string, opts QueryOptions) ([]Result, bool, error) {
	if opts.TopK == 0 {
		opts.TopK = defaultTopK
	}

	rawLower := strings.ToLower(q)
	queryGrams := idx.analyzer.AnalyzeQuery(q)

	if len(queryGrams) == 0 {
		return nil, false, nil
	}

	docs := idx.snapshot()

	type candidate struct {
		rec   *docRecord
		score float64
	}
	var candidates []candidate

	for _, rec := range docs {
		if ctx.Err() != nil {
			return nil, false, ctx.Err()
		}
		score := scoreDoc(rec, queryGrams, rawLower)
		if score == 0 {
			continue
		}
		candidates = append(candidates, candidate{rec: rec, score: score})
	}

	sort.Slice(candidates, func(i, j int) bool {
		return candidates[i].score > candidates[j].score
	})

	truncated := len(candidates) > opts.TopK
	if truncated {
		candidates = candidates[:opts.TopK]
	}

	results := make([]Result, 0, len(candidates))
	for _, c := range candidates {
		if ctx.Err() != nil {
			return results, truncated, ctx.Err()
		}
		url := buildResultURL(opts.VaultPrefix, c.rec.path)
		snippet, highlights := generateSnippet(opts.VaultRoot, c.rec.path, rawLower)
		results = append(results, Result{
			Path:       c.rec.path,
			URL:        url,
			Title:      c.rec.title,
			Score:      c.score,
			Snippet:    snippet,
			Highlights: highlights,
		})
	}
	return results, truncated, nil
}

// scoreDoc computes the ranking score for one document against the query gram
// set and the raw lowercase query string. Returns 0 when coverage falls below
// the floor (doc excluded).
func scoreDoc(rec *docRecord, queryGrams []uint32, rawLower string) float64 {
	if len(queryGrams) == 0 {
		return 0
	}

	// Coverage: query containment = |Q ∩ doc.grams| / |Q|.
	// We check body + title + tag grams combined (union of all doc grams).
	bodyHits := intersectLen(queryGrams, rec.grams)
	titleHits := intersectLen(queryGrams, rec.titleGrams)
	tagHits := intersectLen(queryGrams, rec.tagGrams)

	// Union coverage: how many distinct query grams appear in ANY field.
	allHits := unionIntersectLen(queryGrams, rec.grams, rec.titleGrams, rec.tagGrams)
	coverage := float64(allHits) / float64(len(queryGrams))
	if coverage < coverageFloor {
		return 0
	}

	score := coverage

	// Field boosts.
	const (
		boostTitle = 0.5
		boostTag   = 0.3
		boostPath  = 0.1
		boostExact = 0.4
	)

	// Fractional boost proportional to query grams found in that field.
	qf := float64(len(queryGrams))
	if titleHits > 0 {
		score += boostTitle * float64(titleHits) / qf
	}
	if tagHits > 0 {
		score += boostTag * float64(tagHits) / qf
	}
	_ = bodyHits

	// Path-substring boost.
	if strings.Contains(strings.ToLower(rec.path), rawLower) {
		score += boostPath
	}

	// Exact-substring bonus (checked on candidates that already passed
	// coverage floor, so this is cheap).
	titleLower := strings.ToLower(rec.title)
	if strings.Contains(titleLower, rawLower) {
		score += boostExact
	}

	return score
}

// unionIntersectLen counts how many IDs from query appear in at least one
// of a, b, or c (all sorted). This is the union-coverage numerator.
func unionIntersectLen(query, a, b, c []uint32) int {
	if len(query) == 0 {
		return 0
	}
	n := 0
	for _, id := range query {
		if sortedContains(a, id) || sortedContains(b, id) || sortedContains(c, id) {
			n++
		}
	}
	return n
}

// sortedContains reports whether sorted slice s contains v. Binary search.
func sortedContains(s []uint32, v uint32) bool {
	lo, hi := 0, len(s)
	for lo < hi {
		mid := (lo + hi) / 2
		switch {
		case s[mid] == v:
			return true
		case s[mid] < v:
			lo = mid + 1
		default:
			hi = mid
		}
	}
	return false
}

// buildResultURL converts a vault-relative file path to the web URL the
// reader would serve it at.
func buildResultURL(vaultPrefix, relPath string) string {
	stripped := strings.TrimSuffix(relPath, ".md")
	if vaultPrefix == "/" || vaultPrefix == "" {
		return "/" + stripped
	}
	return vaultPrefix + "/" + stripped
}

// generateSnippet reads the file at vaultRoot/relPath, finds the line or
// sliding window with the most query word occurrences (case-insensitive
// substring), and returns ~160 chars with match offsets.
func generateSnippet(vaultRoot, relPath, rawLower string) (string, [][2]int) {
	fullPath := filepath.Join(vaultRoot, relPath)
	f, err := os.Open(fullPath)
	if err != nil {
		return "", nil
	}
	defer f.Close()

	// Split the query into individual words for "most words in window" scoring.
	qWords := strings.Fields(rawLower)
	if len(qWords) == 0 {
		qWords = []string{rawLower}
	}

	// Collect lines.
	var lines []string
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		lines = append(lines, scanner.Text())
	}

	if len(lines) == 0 {
		return "", nil
	}

	// Score each line by number of distinct query words it contains.
	bestLine := ""
	bestScore := -1
	for _, line := range lines {
		ll := strings.ToLower(line)
		score := 0
		for _, w := range qWords {
			if strings.Contains(ll, w) {
				score++
			}
		}
		if score > bestScore {
			bestScore = score
			bestLine = line
		}
	}

	if bestLine == "" {
		// Fall back to first non-empty line.
		for _, l := range lines {
			if strings.TrimSpace(l) != "" {
				bestLine = l
				break
			}
		}
	}

	// Trim to snippetLen runes, centering around first match if possible.
	snippet, highlights := trimSnippet(bestLine, rawLower, qWords)
	return snippet, highlights
}

// trimSnippet trims line to ~snippetLen chars around the first query match
// and computes match highlights as rune (code-point) offsets in the returned
// snippet, so JS clients (which index strings by code point) align highlights
// across multi-byte runes such as Polish ł.
func trimSnippet(line, rawLower string, qWords []string) (string, [][2]int) {
	runes := []rune(line)
	lineLower := strings.ToLower(line)

	// Find first match position in runes.
	firstMatch := -1
	for _, w := range qWords {
		if idx := strings.Index(lineLower, w); idx >= 0 {
			// Convert byte offset to rune offset.
			runeIdx := runeLen(line[:idx])
			if firstMatch < 0 || runeIdx < firstMatch {
				firstMatch = runeIdx
			}
		}
	}

	// Compute rune window around the first match.
	start := 0
	if firstMatch > snippetLen/2 {
		start = firstMatch - snippetLen/2
	}
	end := start + snippetLen
	if end > len(runes) {
		end = len(runes)
		if end-snippetLen > 0 {
			start = end - snippetLen
		}
	}
	snippet := string(runes[start:end])

	// Find highlight offsets in the snippet string (byte offsets).
	snipLower := strings.ToLower(snippet)
	seen := make(map[[2]int]struct{})
	var highlights [][2]int
	for _, w := range qWords {
		s := 0
		for {
			idx := strings.Index(snipLower[s:], w)
			if idx < 0 {
				break
			}
			byteStart := s + idx
			byteEnd := byteStart + len(w)
			key := [2]int{byteStart, byteEnd}
			if _, dup := seen[key]; !dup {
				seen[key] = struct{}{}
				highlights = append(highlights, key)
			}
			s = byteStart + 1
		}
	}
	sort.Slice(highlights, func(i, j int) bool {
		return highlights[i][0] < highlights[j][0]
	})

	// Also check for the raw query as a whole string.
	if !bytes.Contains([]byte(snipLower), []byte(rawLower)) {
		// rawLower is covered by the individual word loop above if it's one word.
		// If it's a phrase and appears as a whole, add its highlights too.
	} else if len(strings.Fields(rawLower)) > 1 {
		s := 0
		for {
			idx := strings.Index(snipLower[s:], rawLower)
			if idx < 0 {
				break
			}
			byteStart := s + idx
			byteEnd := byteStart + len(rawLower)
			key := [2]int{byteStart, byteEnd}
			if _, dup := seen[key]; !dup {
				seen[key] = struct{}{}
				highlights = append(highlights, key)
			}
			s = byteStart + 1
		}
		sort.Slice(highlights, func(i, j int) bool {
			return highlights[i][0] < highlights[j][0]
		})
	}

	// Convert byte offsets (from strings.Index above) to rune offsets so the
	// client can slice the snippet by code point — see the type doc on Result.
	for i, h := range highlights {
		highlights[i] = [2]int{runeLen(snippet[:h[0]]), runeLen(snippet[:h[1]])}
	}

	return snippet, highlights
}
